app: 
  name: local_financial_management
  version: 1.0.0

mysql_config:
  host: 127.0.0.1
  port: 3306
  username: root
  password: Getshitdone22!
  database: finance

logging:
  level: info
  file: app.log